// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package httpapi

import (
	"code/internal/application"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUseCase creates a new instance of MockUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUseCase {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockUseCase is an autogenerated mock type for the UseCase type
type MockUseCase struct {
	mock.Mock
}

type MockUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUseCase) EXPECT() *MockUseCase_Expecter {
	return &MockUseCase_Expecter{mock: &_m.Mock}
}

// CreateLink provides a mock function for the type MockUseCase
func (_mock *MockUseCase) CreateLink(ctx context.Context, in application.LinkInput) (application.Link, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for CreateLink")
	}

	var r0 application.Link
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, application.LinkInput) (application.Link, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, application.LinkInput) application.Link); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(application.Link)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, application.LinkInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUseCase_CreateLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateLink'
type MockUseCase_CreateLink_Call struct {
	*mock.Call
}

// CreateLink is a helper method to define mock.On call
//   - ctx context.Context
//   - in application.LinkInput
func (_e *MockUseCase_Expecter) CreateLink(ctx any, in any) *MockUseCase_CreateLink_Call {
	return &MockUseCase_CreateLink_Call{Call: _e.mock.On("CreateLink", ctx, in)}
}

func (_c *MockUseCase_CreateLink_Call) Run(run func(ctx context.Context, in application.LinkInput)) *MockUseCase_CreateLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 application.LinkInput
		if args[1] != nil {
			arg1 = args[1].(application.LinkInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUseCase_CreateLink_Call) Return(link application.Link, err error) *MockUseCase_CreateLink_Call {
	_c.Call.Return(link, err)
	return _c
}

func (_c *MockUseCase_CreateLink_Call) RunAndReturn(run func(ctx context.Context, in application.LinkInput) (application.Link, error)) *MockUseCase_CreateLink_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteLink provides a mock function for the type MockUseCase
func (_mock *MockUseCase) DeleteLink(ctx context.Context, id int64) (application.Link, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLink")
	}

	var r0 application.Link
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (application.Link, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) application.Link); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(application.Link)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUseCase_DeleteLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteLink'
type MockUseCase_DeleteLink_Call struct {
	*mock.Call
}

// DeleteLink is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockUseCase_Expecter) DeleteLink(ctx any, id any) *MockUseCase_DeleteLink_Call {
	return &MockUseCase_DeleteLink_Call{Call: _e.mock.On("DeleteLink", ctx, id)}
}

func (_c *MockUseCase_DeleteLink_Call) Run(run func(ctx context.Context, id int64)) *MockUseCase_DeleteLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUseCase_DeleteLink_Call) Return(link application.Link, err error) *MockUseCase_DeleteLink_Call {
	_c.Call.Return(link, err)
	return _c
}

func (_c *MockUseCase_DeleteLink_Call) RunAndReturn(run func(ctx context.Context, id int64) (application.Link, error)) *MockUseCase_DeleteLink_Call {
	_c.Call.Return(run)
	return _c
}

// GetLinkByID provides a mock function for the type MockUseCase
func (_mock *MockUseCase) GetLinkByID(ctx context.Context, id int64) (application.Link, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetLinkByID")
	}

	var r0 application.Link
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (application.Link, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) application.Link); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(application.Link)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUseCase_GetLinkByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLinkByID'
type MockUseCase_GetLinkByID_Call struct {
	*mock.Call
}

// GetLinkByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockUseCase_Expecter) GetLinkByID(ctx any, id any) *MockUseCase_GetLinkByID_Call {
	return &MockUseCase_GetLinkByID_Call{Call: _e.mock.On("GetLinkByID", ctx, id)}
}

func (_c *MockUseCase_GetLinkByID_Call) Run(run func(ctx context.Context, id int64)) *MockUseCase_GetLinkByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUseCase_GetLinkByID_Call) Return(link application.Link, err error) *MockUseCase_GetLinkByID_Call {
	_c.Call.Return(link, err)
	return _c
}

func (_c *MockUseCase_GetLinkByID_Call) RunAndReturn(run func(ctx context.Context, id int64) (application.Link, error)) *MockUseCase_GetLinkByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetLinkByShortName provides a mock function for the type MockUseCase
func (_mock *MockUseCase) GetLinkByShortName(ctx context.Context, shortName string) (application.Link, error) {
	ret := _mock.Called(ctx, shortName)

	if len(ret) == 0 {
		panic("no return value specified for GetLinkByShortName")
	}

	var r0 application.Link
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (application.Link, error)); ok {
		return returnFunc(ctx, shortName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) application.Link); ok {
		r0 = returnFunc(ctx, shortName)
	} else {
		r0 = ret.Get(0).(application.Link)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, shortName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUseCase_GetLinkByShortName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLinkByShortName'
type MockUseCase_GetLinkByShortName_Call struct {
	*mock.Call
}

// GetLinkByShortName is a helper method to define mock.On call
//   - ctx context.Context
//   - shortName string
func (_e *MockUseCase_Expecter) GetLinkByShortName(ctx any, shortName any) *MockUseCase_GetLinkByShortName_Call {
	return &MockUseCase_GetLinkByShortName_Call{Call: _e.mock.On("GetLinkByShortName", ctx, shortName)}
}

func (_c *MockUseCase_GetLinkByShortName_Call) Run(run func(ctx context.Context, shortName string)) *MockUseCase_GetLinkByShortName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUseCase_GetLinkByShortName_Call) Return(link application.Link, err error) *MockUseCase_GetLinkByShortName_Call {
	_c.Call.Return(link, err)
	return _c
}

func (_c *MockUseCase_GetLinkByShortName_Call) RunAndReturn(run func(ctx context.Context, shortName string) (application.Link, error)) *MockUseCase_GetLinkByShortName_Call {
	_c.Call.Return(run)
	return _c
}

// PageLinkVisits provides a mock function for the type MockUseCase
func (_mock *MockUseCase) PageLinkVisits(ctx context.Context, q application.PageQuery) (application.RangePage[application.Visit], error) {
	ret := _mock.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for PageLinkVisits")
	}

	var r0 application.RangePage[application.Visit]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, application.PageQuery) (application.RangePage[application.Visit], error)); ok {
		return returnFunc(ctx, q)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, application.PageQuery) application.RangePage[application.Visit]); ok {
		r0 = returnFunc(ctx, q)
	} else {
		r0 = ret.Get(0).(application.RangePage[application.Visit])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, application.PageQuery) error); ok {
		r1 = returnFunc(ctx, q)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUseCase_PageLinkVisits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PageLinkVisits'
type MockUseCase_PageLinkVisits_Call struct {
	*mock.Call
}

// PageLinkVisits is a helper method to define mock.On call
//   - ctx context.Context
//   - q application.PageQuery
func (_e *MockUseCase_Expecter) PageLinkVisits(ctx any, q any) *MockUseCase_PageLinkVisits_Call {
	return &MockUseCase_PageLinkVisits_Call{Call: _e.mock.On("PageLinkVisits", ctx, q)}
}

func (_c *MockUseCase_PageLinkVisits_Call) Run(run func(ctx context.Context, q application.PageQuery)) *MockUseCase_PageLinkVisits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 application.PageQuery
		if args[1] != nil {
			arg1 = args[1].(application.PageQuery)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUseCase_PageLinkVisits_Call) Return(rangePage application.RangePage[application.Visit], err error) *MockUseCase_PageLinkVisits_Call {
	_c.Call.Return(rangePage, err)
	return _c
}

func (_c *MockUseCase_PageLinkVisits_Call) RunAndReturn(run func(ctx context.Context, q application.PageQuery) (application.RangePage[application.Visit], error)) *MockUseCase_PageLinkVisits_Call {
	_c.Call.Return(run)
	return _c
}

// PageLinks provides a mock function for the type MockUseCase
func (_mock *MockUseCase) PageLinks(ctx context.Context, q application.PageQuery) (application.RangePage[application.Link], error) {
	ret := _mock.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for PageLinks")
	}

	var r0 application.RangePage[application.Link]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, application.PageQuery) (application.RangePage[application.Link], error)); ok {
		return returnFunc(ctx, q)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, application.PageQuery) application.RangePage[application.Link]); ok {
		r0 = returnFunc(ctx, q)
	} else {
		r0 = ret.Get(0).(application.RangePage[application.Link])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, application.PageQuery) error); ok {
		r1 = returnFunc(ctx, q)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUseCase_PageLinks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PageLinks'
type MockUseCase_PageLinks_Call struct {
	*mock.Call
}

// PageLinks is a helper method to define mock.On call
//   - ctx context.Context
//   - q application.PageQuery
func (_e *MockUseCase_Expecter) PageLinks(ctx any, q any) *MockUseCase_PageLinks_Call {
	return &MockUseCase_PageLinks_Call{Call: _e.mock.On("PageLinks", ctx, q)}
}

func (_c *MockUseCase_PageLinks_Call) Run(run func(ctx context.Context, q application.PageQuery)) *MockUseCase_PageLinks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 application.PageQuery
		if args[1] != nil {
			arg1 = args[1].(application.PageQuery)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUseCase_PageLinks_Call) Return(rangePage application.RangePage[application.Link], err error) *MockUseCase_PageLinks_Call {
	_c.Call.Return(rangePage, err)
	return _c
}

func (_c *MockUseCase_PageLinks_Call) RunAndReturn(run func(ctx context.Context, q application.PageQuery) (application.RangePage[application.Link], error)) *MockUseCase_PageLinks_Call {
	_c.Call.Return(run)
	return _c
}

// Redirect provides a mock function for the type MockUseCase
func (_mock *MockUseCase) Redirect(ctx context.Context, shortName string, visit application.VisitInput) (application.Link, error) {
	ret := _mock.Called(ctx, shortName, visit)

	if len(ret) == 0 {
		panic("no return value specified for Redirect")
	}

	var r0 application.Link
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, application.VisitInput) (application.Link, error)); ok {
		return returnFunc(ctx, shortName, visit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, application.VisitInput) application.Link); ok {
		r0 = returnFunc(ctx, shortName, visit)
	} else {
		r0 = ret.Get(0).(application.Link)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, application.VisitInput) error); ok {
		r1 = returnFunc(ctx, shortName, visit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUseCase_Redirect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Redirect'
type MockUseCase_Redirect_Call struct {
	*mock.Call
}

// Redirect is a helper method to define mock.On call
//   - ctx context.Context
//   - shortName string
//   - visit application.VisitInput
func (_e *MockUseCase_Expecter) Redirect(ctx any, shortName any, visit any) *MockUseCase_Redirect_Call {
	return &MockUseCase_Redirect_Call{Call: _e.mock.On("Redirect", ctx, shortName, visit)}
}

func (_c *MockUseCase_Redirect_Call) Run(run func(ctx context.Context, shortName string, visit application.VisitInput)) *MockUseCase_Redirect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 application.VisitInput
		if args[2] != nil {
			arg2 = args[2].(application.VisitInput)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUseCase_Redirect_Call) Return(link application.Link, err error) *MockUseCase_Redirect_Call {
	_c.Call.Return(link, err)
	return _c
}

func (_c *MockUseCase_Redirect_Call) RunAndReturn(run func(ctx context.Context, shortName string, visit application.VisitInput) (application.Link, error)) *MockUseCase_Redirect_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateLink provides a mock function for the type MockUseCase
func (_mock *MockUseCase) UpdateLink(ctx context.Context, id int64, in application.LinkInput) (application.Link, error) {
	ret := _mock.Called(ctx, id, in)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLink")
	}

	var r0 application.Link
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, application.LinkInput) (application.Link, error)); ok {
		return returnFunc(ctx, id, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, application.LinkInput) application.Link); ok {
		r0 = returnFunc(ctx, id, in)
	} else {
		r0 = ret.Get(0).(application.Link)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, application.LinkInput) error); ok {
		r1 = returnFunc(ctx, id, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUseCase_UpdateLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLink'
type MockUseCase_UpdateLink_Call struct {
	*mock.Call
}

// UpdateLink is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - in application.LinkInput
func (_e *MockUseCase_Expecter) UpdateLink(ctx any, id any, in any) *MockUseCase_UpdateLink_Call {
	return &MockUseCase_UpdateLink_Call{Call: _e.mock.On("UpdateLink", ctx, id, in)}
}

func (_c *MockUseCase_UpdateLink_Call) Run(run func(ctx context.Context, id int64, in application.LinkInput)) *MockUseCase_UpdateLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 application.LinkInput
		if args[2] != nil {
			arg2 = args[2].(application.LinkInput)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUseCase_UpdateLink_Call) Return(link application.Link, err error) *MockUseCase_UpdateLink_Call {
	_c.Call.Return(link, err)
	return _c
}

func (_c *MockUseCase_UpdateLink_Call) RunAndReturn(run func(ctx context.Context, id int64, in application.LinkInput) (application.Link, error)) *MockUseCase_UpdateLink_Call {
	_c.Call.Return(run)
	return _c
}
