version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: standard
  enable:
    - nlreturn
    - gocritic
    - errcheck
    - staticcheck
    - gocyclo
    - revive
    - goconst
    - unparam
    - ineffassign
    - unused
    - misspell
    - lll
  settings:
    goconst:
      ignore-tests: true
    nlreturn:
      block-size: 3
    lll:
      line-length: 120
      skip-comments: true
      tab-width: 1

formatters:
  enable:
    - gofmt
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(code)