version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: standard
  enable:
    - nlreturn
    - gocritic
    - errcheck
    - staticcheck
    - gocyclo
    - revive
    - goconst
    - unparam
    - ineffassign
    - unused
    - misspell
  settings:
    nlreturn:
      block-size: 3

formatters:
  enable:
    - gofmt
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(code)