sonar.projectKey=dark7lord_go-project-278
sonar.organization=dark7lord

sonar.sources=.
sonar.exclusions=**/*_test.go
sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.host.url=https://sonarcloud.io
sonar.go.coverage.reportPaths=coverage.out
