// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package application

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockLinkStore creates a new instance of MockLinkStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLinkStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLinkStore {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockLinkStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockLinkStore is an autogenerated mock type for the LinkStore type
type MockLinkStore struct {
	mock.Mock
}

type MockLinkStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLinkStore) EXPECT() *MockLinkStore_Expecter {
	return &MockLinkStore_Expecter{mock: &_m.Mock}
}

// CreateLink provides a mock function for the type MockLinkStore
func (_mock *MockLinkStore) CreateLink(ctx context.Context, originalURL string, shortName string) (Link, error) {
	ret := _mock.Called(ctx, originalURL, shortName)

	if len(ret) == 0 {
		panic("no return value specified for CreateLink")
	}

	var r0 Link
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (Link, error)); ok {
		return returnFunc(ctx, originalURL, shortName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) Link); ok {
		r0 = returnFunc(ctx, originalURL, shortName)
	} else {
		r0 = ret.Get(0).(Link)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, originalURL, shortName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLinkStore_CreateLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateLink'
type MockLinkStore_CreateLink_Call struct {
	*mock.Call
}

// CreateLink is a helper method to define mock.On call
//   - ctx context.Context
//   - originalURL string
//   - shortName string
func (_e *MockLinkStore_Expecter) CreateLink(ctx any, originalURL any, shortName any) *MockLinkStore_CreateLink_Call {
	return &MockLinkStore_CreateLink_Call{Call: _e.mock.On("CreateLink", ctx, originalURL, shortName)}
}

func (_c *MockLinkStore_CreateLink_Call) Run(run func(ctx context.Context, originalURL string, shortName string)) *MockLinkStore_CreateLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockLinkStore_CreateLink_Call) Return(link Link, err error) *MockLinkStore_CreateLink_Call {
	_c.Call.Return(link, err)
	return _c
}

func (_c *MockLinkStore_CreateLink_Call) RunAndReturn(run func(ctx context.Context, originalURL string, shortName string) (Link, error)) *MockLinkStore_CreateLink_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteLink provides a mock function for the type MockLinkStore
func (_mock *MockLinkStore) DeleteLink(ctx context.Context, id int64) (Link, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLink")
	}

	var r0 Link
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (Link, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) Link); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(Link)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLinkStore_DeleteLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteLink'
type MockLinkStore_DeleteLink_Call struct {
	*mock.Call
}

// DeleteLink is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockLinkStore_Expecter) DeleteLink(ctx any, id any) *MockLinkStore_DeleteLink_Call {
	return &MockLinkStore_DeleteLink_Call{Call: _e.mock.On("DeleteLink", ctx, id)}
}

func (_c *MockLinkStore_DeleteLink_Call) Run(run func(ctx context.Context, id int64)) *MockLinkStore_DeleteLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLinkStore_DeleteLink_Call) Return(link Link, err error) *MockLinkStore_DeleteLink_Call {
	_c.Call.Return(link, err)
	return _c
}

func (_c *MockLinkStore_DeleteLink_Call) RunAndReturn(run func(ctx context.Context, id int64) (Link, error)) *MockLinkStore_DeleteLink_Call {
	_c.Call.Return(run)
	return _c
}

// GetLinkByID provides a mock function for the type MockLinkStore
func (_mock *MockLinkStore) GetLinkByID(ctx context.Context, id int64) (Link, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetLinkByID")
	}

	var r0 Link
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (Link, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) Link); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(Link)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLinkStore_GetLinkByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLinkByID'
type MockLinkStore_GetLinkByID_Call struct {
	*mock.Call
}

// GetLinkByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockLinkStore_Expecter) GetLinkByID(ctx any, id any) *MockLinkStore_GetLinkByID_Call {
	return &MockLinkStore_GetLinkByID_Call{Call: _e.mock.On("GetLinkByID", ctx, id)}
}

func (_c *MockLinkStore_GetLinkByID_Call) Run(run func(ctx context.Context, id int64)) *MockLinkStore_GetLinkByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLinkStore_GetLinkByID_Call) Return(link Link, err error) *MockLinkStore_GetLinkByID_Call {
	_c.Call.Return(link, err)
	return _c
}

func (_c *MockLinkStore_GetLinkByID_Call) RunAndReturn(run func(ctx context.Context, id int64) (Link, error)) *MockLinkStore_GetLinkByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetLinkByShortName provides a mock function for the type MockLinkStore
func (_mock *MockLinkStore) GetLinkByShortName(ctx context.Context, shortName string) (Link, error) {
	ret := _mock.Called(ctx, shortName)

	if len(ret) == 0 {
		panic("no return value specified for GetLinkByShortName")
	}

	var r0 Link
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (Link, error)); ok {
		return returnFunc(ctx, shortName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) Link); ok {
		r0 = returnFunc(ctx, shortName)
	} else {
		r0 = ret.Get(0).(Link)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, shortName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLinkStore_GetLinkByShortName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLinkByShortName'
type MockLinkStore_GetLinkByShortName_Call struct {
	*mock.Call
}

// GetLinkByShortName is a helper method to define mock.On call
//   - ctx context.Context
//   - shortName string
func (_e *MockLinkStore_Expecter) GetLinkByShortName(ctx any, shortName any) *MockLinkStore_GetLinkByShortName_Call {
	return &MockLinkStore_GetLinkByShortName_Call{Call: _e.mock.On("GetLinkByShortName", ctx, shortName)}
}

func (_c *MockLinkStore_GetLinkByShortName_Call) Run(run func(ctx context.Context, shortName string)) *MockLinkStore_GetLinkByShortName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLinkStore_GetLinkByShortName_Call) Return(link Link, err error) *MockLinkStore_GetLinkByShortName_Call {
	_c.Call.Return(link, err)
	return _c
}

func (_c *MockLinkStore_GetLinkByShortName_Call) RunAndReturn(run func(ctx context.Context, shortName string) (Link, error)) *MockLinkStore_GetLinkByShortName_Call {
	_c.Call.Return(run)
	return _c
}

// PageLinks provides a mock function for the type MockLinkStore
func (_mock *MockLinkStore) PageLinks(ctx context.Context, q PageQuery) (RangePage[Link], error) {
	ret := _mock.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for PageLinks")
	}

	var r0 RangePage[Link]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, PageQuery) (RangePage[Link], error)); ok {
		return returnFunc(ctx, q)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, PageQuery) RangePage[Link]); ok {
		r0 = returnFunc(ctx, q)
	} else {
		r0 = ret.Get(0).(RangePage[Link])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, PageQuery) error); ok {
		r1 = returnFunc(ctx, q)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLinkStore_PageLinks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PageLinks'
type MockLinkStore_PageLinks_Call struct {
	*mock.Call
}

// PageLinks is a helper method to define mock.On call
//   - ctx context.Context
//   - q PageQuery
func (_e *MockLinkStore_Expecter) PageLinks(ctx any, q any) *MockLinkStore_PageLinks_Call {
	return &MockLinkStore_PageLinks_Call{Call: _e.mock.On("PageLinks", ctx, q)}
}

func (_c *MockLinkStore_PageLinks_Call) Run(run func(ctx context.Context, q PageQuery)) *MockLinkStore_PageLinks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 PageQuery
		if args[1] != nil {
			arg1 = args[1].(PageQuery)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLinkStore_PageLinks_Call) Return(rangePage RangePage[Link], err error) *MockLinkStore_PageLinks_Call {
	_c.Call.Return(rangePage, err)
	return _c
}

func (_c *MockLinkStore_PageLinks_Call) RunAndReturn(run func(ctx context.Context, q PageQuery) (RangePage[Link], error)) *MockLinkStore_PageLinks_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateLink provides a mock function for the type MockLinkStore
func (_mock *MockLinkStore) UpdateLink(ctx context.Context, id int64, originalURL string, shortName string) (Link, error) {
	ret := _mock.Called(ctx, id, originalURL, shortName)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLink")
	}

	var r0 Link
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, string) (Link, error)); ok {
		return returnFunc(ctx, id, originalURL, shortName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, string) Link); ok {
		r0 = returnFunc(ctx, id, originalURL, shortName)
	} else {
		r0 = ret.Get(0).(Link)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string, string) error); ok {
		r1 = returnFunc(ctx, id, originalURL, shortName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLinkStore_UpdateLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLink'
type MockLinkStore_UpdateLink_Call struct {
	*mock.Call
}

// UpdateLink is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - originalURL string
//   - shortName string
func (_e *MockLinkStore_Expecter) UpdateLink(ctx any, id any, originalURL any, shortName any) *MockLinkStore_UpdateLink_Call {
	return &MockLinkStore_UpdateLink_Call{Call: _e.mock.On("UpdateLink", ctx, id, originalURL, shortName)}
}

func (_c *MockLinkStore_UpdateLink_Call) Run(run func(ctx context.Context, id int64, originalURL string, shortName string)) *MockLinkStore_UpdateLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockLinkStore_UpdateLink_Call) Return(link Link, err error) *MockLinkStore_UpdateLink_Call {
	_c.Call.Return(link, err)
	return _c
}

func (_c *MockLinkStore_UpdateLink_Call) RunAndReturn(run func(ctx context.Context, id int64, originalURL string, shortName string) (Link, error)) *MockLinkStore_UpdateLink_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVisitStore creates a new instance of MockVisitStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVisitStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVisitStore {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockVisitStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockVisitStore is an autogenerated mock type for the VisitStore type
type MockVisitStore struct {
	mock.Mock
}

type MockVisitStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVisitStore) EXPECT() *MockVisitStore_Expecter {
	return &MockVisitStore_Expecter{mock: &_m.Mock}
}

// CreateLinkVisit provides a mock function for the type MockVisitStore
func (_mock *MockVisitStore) CreateLinkVisit(ctx context.Context, linkID int64, visit VisitInput) (Visit, error) {
	ret := _mock.Called(ctx, linkID, visit)

	if len(ret) == 0 {
		panic("no return value specified for CreateLinkVisit")
	}

	var r0 Visit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, VisitInput) (Visit, error)); ok {
		return returnFunc(ctx, linkID, visit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, VisitInput) Visit); ok {
		r0 = returnFunc(ctx, linkID, visit)
	} else {
		r0 = ret.Get(0).(Visit)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, VisitInput) error); ok {
		r1 = returnFunc(ctx, linkID, visit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVisitStore_CreateLinkVisit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateLinkVisit'
type MockVisitStore_CreateLinkVisit_Call struct {
	*mock.Call
}

// CreateLinkVisit is a helper method to define mock.On call
//   - ctx context.Context
//   - linkID int64
//   - visit VisitInput
func (_e *MockVisitStore_Expecter) CreateLinkVisit(ctx any, linkID any, visit any) *MockVisitStore_CreateLinkVisit_Call {
	return &MockVisitStore_CreateLinkVisit_Call{Call: _e.mock.On("CreateLinkVisit", ctx, linkID, visit)}
}

func (_c *MockVisitStore_CreateLinkVisit_Call) Run(run func(ctx context.Context, linkID int64, visit VisitInput)) *MockVisitStore_CreateLinkVisit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 VisitInput
		if args[2] != nil {
			arg2 = args[2].(VisitInput)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockVisitStore_CreateLinkVisit_Call) Return(visit1 Visit, err error) *MockVisitStore_CreateLinkVisit_Call {
	_c.Call.Return(visit1, err)
	return _c
}

func (_c *MockVisitStore_CreateLinkVisit_Call) RunAndReturn(run func(ctx context.Context, linkID int64, visit VisitInput) (Visit, error)) *MockVisitStore_CreateLinkVisit_Call {
	_c.Call.Return(run)
	return _c
}

// PageLinkVisits provides a mock function for the type MockVisitStore
func (_mock *MockVisitStore) PageLinkVisits(ctx context.Context, q PageQuery) (RangePage[Visit], error) {
	ret := _mock.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for PageLinkVisits")
	}

	var r0 RangePage[Visit]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, PageQuery) (RangePage[Visit], error)); ok {
		return returnFunc(ctx, q)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, PageQuery) RangePage[Visit]); ok {
		r0 = returnFunc(ctx, q)
	} else {
		r0 = ret.Get(0).(RangePage[Visit])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, PageQuery) error); ok {
		r1 = returnFunc(ctx, q)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVisitStore_PageLinkVisits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PageLinkVisits'
type MockVisitStore_PageLinkVisits_Call struct {
	*mock.Call
}

// PageLinkVisits is a helper method to define mock.On call
//   - ctx context.Context
//   - q PageQuery
func (_e *MockVisitStore_Expecter) PageLinkVisits(ctx any, q any) *MockVisitStore_PageLinkVisits_Call {
	return &MockVisitStore_PageLinkVisits_Call{Call: _e.mock.On("PageLinkVisits", ctx, q)}
}

func (_c *MockVisitStore_PageLinkVisits_Call) Run(run func(ctx context.Context, q PageQuery)) *MockVisitStore_PageLinkVisits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 PageQuery
		if args[1] != nil {
			arg1 = args[1].(PageQuery)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVisitStore_PageLinkVisits_Call) Return(rangePage RangePage[Visit], err error) *MockVisitStore_PageLinkVisits_Call {
	_c.Call.Return(rangePage, err)
	return _c
}

func (_c *MockVisitStore_PageLinkVisits_Call) RunAndReturn(run func(ctx context.Context, q PageQuery) (RangePage[Visit], error)) *MockVisitStore_PageLinkVisits_Call {
	_c.Call.Return(run)
	return _c
}
