// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package application

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockLinkWriter creates a new instance of MockLinkWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLinkWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLinkWriter {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockLinkWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockLinkWriter is an autogenerated mock type for the LinkWriter type
type MockLinkWriter struct {
	mock.Mock
}

type MockLinkWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLinkWriter) EXPECT() *MockLinkWriter_Expecter {
	return &MockLinkWriter_Expecter{mock: &_m.Mock}
}

// CreateLink provides a mock function for the type MockLinkWriter
func (_mock *MockLinkWriter) CreateLink(ctx context.Context, originalURL string, shortName string) (LinkView, error) {
	ret := _mock.Called(ctx, originalURL, shortName)

	if len(ret) == 0 {
		panic("no return value specified for CreateLink")
	}

	var r0 LinkView
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (LinkView, error)); ok {
		return returnFunc(ctx, originalURL, shortName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) LinkView); ok {
		r0 = returnFunc(ctx, originalURL, shortName)
	} else {
		r0 = ret.Get(0).(LinkView)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, originalURL, shortName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLinkWriter_CreateLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateLink'
type MockLinkWriter_CreateLink_Call struct {
	*mock.Call
}

// CreateLink is a helper method to define mock.On call
//   - ctx context.Context
//   - originalURL string
//   - shortName string
func (_e *MockLinkWriter_Expecter) CreateLink(ctx any, originalURL any, shortName any) *MockLinkWriter_CreateLink_Call {
	return &MockLinkWriter_CreateLink_Call{Call: _e.mock.On("CreateLink", ctx, originalURL, shortName)}
}

func (_c *MockLinkWriter_CreateLink_Call) Run(run func(ctx context.Context, originalURL string, shortName string)) *MockLinkWriter_CreateLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockLinkWriter_CreateLink_Call) Return(linkView LinkView, err error) *MockLinkWriter_CreateLink_Call {
	_c.Call.Return(linkView, err)
	return _c
}

func (_c *MockLinkWriter_CreateLink_Call) RunAndReturn(run func(ctx context.Context, originalURL string, shortName string) (LinkView, error)) *MockLinkWriter_CreateLink_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteLink provides a mock function for the type MockLinkWriter
func (_mock *MockLinkWriter) DeleteLink(ctx context.Context, id int64) (LinkView, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLink")
	}

	var r0 LinkView
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (LinkView, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) LinkView); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(LinkView)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLinkWriter_DeleteLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteLink'
type MockLinkWriter_DeleteLink_Call struct {
	*mock.Call
}

// DeleteLink is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockLinkWriter_Expecter) DeleteLink(ctx any, id any) *MockLinkWriter_DeleteLink_Call {
	return &MockLinkWriter_DeleteLink_Call{Call: _e.mock.On("DeleteLink", ctx, id)}
}

func (_c *MockLinkWriter_DeleteLink_Call) Run(run func(ctx context.Context, id int64)) *MockLinkWriter_DeleteLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLinkWriter_DeleteLink_Call) Return(linkView LinkView, err error) *MockLinkWriter_DeleteLink_Call {
	_c.Call.Return(linkView, err)
	return _c
}

func (_c *MockLinkWriter_DeleteLink_Call) RunAndReturn(run func(ctx context.Context, id int64) (LinkView, error)) *MockLinkWriter_DeleteLink_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateLink provides a mock function for the type MockLinkWriter
func (_mock *MockLinkWriter) UpdateLink(ctx context.Context, id int64, originalURL string, shortName string) (LinkView, error) {
	ret := _mock.Called(ctx, id, originalURL, shortName)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLink")
	}

	var r0 LinkView
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, string) (LinkView, error)); ok {
		return returnFunc(ctx, id, originalURL, shortName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, string) LinkView); ok {
		r0 = returnFunc(ctx, id, originalURL, shortName)
	} else {
		r0 = ret.Get(0).(LinkView)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string, string) error); ok {
		r1 = returnFunc(ctx, id, originalURL, shortName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLinkWriter_UpdateLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLink'
type MockLinkWriter_UpdateLink_Call struct {
	*mock.Call
}

// UpdateLink is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - originalURL string
//   - shortName string
func (_e *MockLinkWriter_Expecter) UpdateLink(ctx any, id any, originalURL any, shortName any) *MockLinkWriter_UpdateLink_Call {
	return &MockLinkWriter_UpdateLink_Call{Call: _e.mock.On("UpdateLink", ctx, id, originalURL, shortName)}
}

func (_c *MockLinkWriter_UpdateLink_Call) Run(run func(ctx context.Context, id int64, originalURL string, shortName string)) *MockLinkWriter_UpdateLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockLinkWriter_UpdateLink_Call) Return(linkView LinkView, err error) *MockLinkWriter_UpdateLink_Call {
	_c.Call.Return(linkView, err)
	return _c
}

func (_c *MockLinkWriter_UpdateLink_Call) RunAndReturn(run func(ctx context.Context, id int64, originalURL string, shortName string) (LinkView, error)) *MockLinkWriter_UpdateLink_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVisitRecorder creates a new instance of MockVisitRecorder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVisitRecorder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVisitRecorder {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockVisitRecorder{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockVisitRecorder is an autogenerated mock type for the VisitRecorder type
type MockVisitRecorder struct {
	mock.Mock
}

type MockVisitRecorder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVisitRecorder) EXPECT() *MockVisitRecorder_Expecter {
	return &MockVisitRecorder_Expecter{mock: &_m.Mock}
}

// CreateLinkVisit provides a mock function for the type MockVisitRecorder
func (_mock *MockVisitRecorder) CreateLinkVisit(ctx context.Context, linkID int64, visit Visit) (VisitView, error) {
	ret := _mock.Called(ctx, linkID, visit)

	if len(ret) == 0 {
		panic("no return value specified for CreateLinkVisit")
	}

	var r0 VisitView
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, Visit) (VisitView, error)); ok {
		return returnFunc(ctx, linkID, visit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, Visit) VisitView); ok {
		r0 = returnFunc(ctx, linkID, visit)
	} else {
		r0 = ret.Get(0).(VisitView)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, Visit) error); ok {
		r1 = returnFunc(ctx, linkID, visit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVisitRecorder_CreateLinkVisit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateLinkVisit'
type MockVisitRecorder_CreateLinkVisit_Call struct {
	*mock.Call
}

// CreateLinkVisit is a helper method to define mock.On call
//   - ctx context.Context
//   - linkID int64
//   - visit Visit
func (_e *MockVisitRecorder_Expecter) CreateLinkVisit(ctx any, linkID any, visit any) *MockVisitRecorder_CreateLinkVisit_Call {
	return &MockVisitRecorder_CreateLinkVisit_Call{Call: _e.mock.On("CreateLinkVisit", ctx, linkID, visit)}
}

func (_c *MockVisitRecorder_CreateLinkVisit_Call) Run(run func(ctx context.Context, linkID int64, visit Visit)) *MockVisitRecorder_CreateLinkVisit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 Visit
		if args[2] != nil {
			arg2 = args[2].(Visit)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockVisitRecorder_CreateLinkVisit_Call) Return(visitView VisitView, err error) *MockVisitRecorder_CreateLinkVisit_Call {
	_c.Call.Return(visitView, err)
	return _c
}

func (_c *MockVisitRecorder_CreateLinkVisit_Call) RunAndReturn(run func(ctx context.Context, linkID int64, visit Visit) (VisitView, error)) *MockVisitRecorder_CreateLinkVisit_Call {
	_c.Call.Return(run)
	return _c
}
