// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: links.sql

package db

import (
	"context"
)

const countLinks = `-- name: CountLinks :one
SELECT COUNT(id) FROM links
`

func (q *Queries) CountLinks(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countLinks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLink = `-- name: CreateLink :one
INSERT INTO links (original_url, short_name, short_url)
VALUES ($1, $2, $3)
RETURNING id, original_url, short_name, short_url
`

type CreateLinkParams struct {
	OriginalURL string `json:"original_url"`
	ShortName   string `json:"short_name"`
	ShortURL    string `json:"short_url"`
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, createLink, arg.OriginalURL, arg.ShortName, arg.ShortURL)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalURL,
		&i.ShortName,
		&i.ShortURL,
	)
	return i, err
}

const deleteLink = `-- name: DeleteLink :one
DELETE FROM links
WHERE id = $1
RETURNING id, original_url, short_name, short_url
`

func (q *Queries) DeleteLink(ctx context.Context, id int64) (Link, error) {
	row := q.db.QueryRow(ctx, deleteLink, id)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalURL,
		&i.ShortName,
		&i.ShortURL,
	)
	return i, err
}

const getLinkByID = `-- name: GetLinkByID :one
SELECT id, original_url, short_name, short_url
FROM links
WHERE id = $1
`

func (q *Queries) GetLinkByID(ctx context.Context, id int64) (Link, error) {
	row := q.db.QueryRow(ctx, getLinkByID, id)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalURL,
		&i.ShortName,
		&i.ShortURL,
	)
	return i, err
}

const getLinkByShortName = `-- name: GetLinkByShortName :one
SELECT id, original_url, short_name, short_url
FROM links
WHERE short_name = $1
`

func (q *Queries) GetLinkByShortName(ctx context.Context, shortName string) (Link, error) {
	row := q.db.QueryRow(ctx, getLinkByShortName, shortName)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalURL,
		&i.ShortName,
		&i.ShortURL,
	)
	return i, err
}

const getLinks = `-- name: GetLinks :many
SELECT id, original_url, short_name, short_url
FROM links
`

func (q *Queries) GetLinks(ctx context.Context) ([]Link, error) {
	rows, err := q.db.Query(ctx, getLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Link
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.OriginalURL,
			&i.ShortName,
			&i.ShortURL,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLinksRange = `-- name: GetLinksRange :many
SELECT id, original_url, short_name, short_url
FROM links
ORDER BY id
OFFSET $1
LIMIT $2
`

type GetLinksRangeParams struct {
	Offset int32 `json:"offset"`
	Limit  int32 `json:"limit"`
}

func (q *Queries) GetLinksRange(ctx context.Context, arg GetLinksRangeParams) ([]Link, error) {
	rows, err := q.db.Query(ctx, getLinksRange, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Link
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.OriginalURL,
			&i.ShortName,
			&i.ShortURL,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShortNames = `-- name: GetShortNames :many
SELECT short_name FROM links
`

func (q *Queries) GetShortNames(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getShortNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var short_name string
		if err := rows.Scan(&short_name); err != nil {
			return nil, err
		}
		items = append(items, short_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShortNamesExcluding = `-- name: GetShortNamesExcluding :many
SELECT short_name FROM links WHERE id != $1
`

func (q *Queries) GetShortNamesExcluding(ctx context.Context, excludeID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, getShortNamesExcluding, excludeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var short_name string
		if err := rows.Scan(&short_name); err != nil {
			return nil, err
		}
		items = append(items, short_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLink = `-- name: UpdateLink :one
UPDATE links
SET
    original_url = $1,
    short_name = $2,
    short_url = $3
WHERE id = $4
RETURNING id, original_url, short_name, short_url
`

type UpdateLinkParams struct {
	OriginalURL string `json:"original_url"`
	ShortName   string `json:"short_name"`
	ShortURL    string `json:"short_url"`
	ID          int64  `json:"id"`
}

func (q *Queries) UpdateLink(ctx context.Context, arg UpdateLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, updateLink,
		arg.OriginalURL,
		arg.ShortName,
		arg.ShortURL,
		arg.ID,
	)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalURL,
		&i.ShortName,
		&i.ShortURL,
	)
	return i, err
}
