// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: links.sql

package db

import (
	"context"
)

const createLink = `-- name: CreateLink :one
INSERT INTO links (original_url, short_name, short_url)
VALUES ($1, $2, $3)
RETURNING id, original_url, short_name, short_url
`

type CreateLinkParams struct {
	OriginalURL string `json:"original_url"`
	ShortName   string `json:"short_name"`
	ShortURL    string `json:"short_url"`
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error) {
	row := q.db.QueryRowContext(ctx, createLink, arg.OriginalURL, arg.ShortName, arg.ShortURL)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalURL,
		&i.ShortName,
		&i.ShortURL,
	)
	return i, err
}

const deleteLink = `-- name: DeleteLink :exec
DELETE FROM links
WHERE id = $1
`

func (q *Queries) DeleteLink(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteLink, id)
	return err
}

const getLink = `-- name: GetLink :one
SELECT id, original_url, short_name, short_url
FROM links
WHERE id = $1
`

func (q *Queries) GetLink(ctx context.Context, id int64) (Link, error) {
	row := q.db.QueryRowContext(ctx, getLink, id)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalURL,
		&i.ShortName,
		&i.ShortURL,
	)
	return i, err
}

const getLinks = `-- name: GetLinks :many
SELECT id, original_url, short_name, short_url
FROM links
`

func (q *Queries) GetLinks(ctx context.Context) ([]Link, error) {
	rows, err := q.db.QueryContext(ctx, getLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Link
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.OriginalURL,
			&i.ShortName,
			&i.ShortURL,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShortNames = `-- name: GetShortNames :many
SELECT short_name FROM links
`

func (q *Queries) GetShortNames(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getShortNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var short_name string
		if err := rows.Scan(&short_name); err != nil {
			return nil, err
		}
		items = append(items, short_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLink = `-- name: UpdateLink :one
UPDATE links
SET
    original_url = $1,
    short_name = $2,
    short_url = $3
WHERE id = $4
RETURNING id, original_url, short_name, short_url
`

type UpdateLinkParams struct {
	OriginalURL string `json:"original_url"`
	ShortName   string `json:"short_name"`
	ShortURL    string `json:"short_url"`
	ID          int64  `json:"id"`
}

func (q *Queries) UpdateLink(ctx context.Context, arg UpdateLinkParams) (Link, error) {
	row := q.db.QueryRowContext(ctx, updateLink,
		arg.OriginalURL,
		arg.ShortName,
		arg.ShortURL,
		arg.ID,
	)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalURL,
		&i.ShortName,
		&i.ShortURL,
	)
	return i, err
}
